# Site settings
title: Dylan Garrido
description: Projecte final DAW
# baseurl: "/projecteDAW" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: dgarrido7
user_description: Estudiante
user_title: Tecnico Superior
email: dylanhurtos@gmail.com
twitter_username: dgarrido_7
github_username:  dgarrido7
# gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
